---
title: "Cyclistic Data Analysis Notebook: Ask Phase"
author: "Donnie Minnick"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
# output: rmarkdown::html_vignette
# vignette: >
#   %\VignetteIndexEntry{prepare}
#   %\VignetteEngine{knitr::rmarkdown}
#   %\VignetteEncoding{UTF-8}
---

## Context

This notebook documents part of a data analysis I completed in the capstone experience for the Google Data Analytics Professional Certificate program on Coursera.

You can find the Github repository for my work [here](https://github.com/dtminnick/cyclistic).

## Ask Phase

This phase involves asking effective questions, using structured thinking, communicating with stakeholders and defining the problem and goal of analysis.

## Background

Cyclistic is a Chicago-based bike-sharing company that has a fleet of bicycles geotracked via a network of stations.  

The company offers customers a variety of bicycles, including options for people with disabilities who can't ride a standard, two-wheel bicycle.  

Cyclistic has two types of riders, casual riders and member riders.  Casual riders are those who purchase single-ride or full-day passes; members are riders that purchase an annual membership.

The majority of riders opt for traditional bicycles; 8% of riders use assistive options.  30% of riders use bicycles to commute to work on a daily basis.

Recent marketing efforts at Cyclistic focused on building awareness and appealing to broad customer segments.

## Problem & Business Task

While offering flexible purchase options attracts customers, Cyclistic's finance department has concluded that members are more profitable than casual riders.  Cyclistic's marketing team plans to develop marketing strategies to convert casual riders to annual members.

The marketing team needs help understanding:

* how annual members and casual riders differ,
* why casual riders might buy an annual membership, and
* how Cyclistic can use digital media to influence casual riders to become members.

The team is requesting three recommendations based on an analysis of their historical data.

## Metrics

Metrics will focus on usage by rider type, and how this usage relates to geography of the city, including:

* volume of rides over time, e.g. hour of day, day of week, week, month,
* measures of ride duration, and
* geographical measures, e.g. common routes used within the city, and how routes relate to cultural, recreational, and other destinations within the city.

## Stakeholders

Key stakeholders include the marketing director, who is responsible for the development of marketing and program promotion, and the executive team, who will approve recommendations made.

## Audience Considerations

Given the stakeholders involved, recommendations are articulated in a short presentation deck, including:

1. statement of the business task and objective,
2. description of data sources used,
3. documentation of data cleaning and manipulation,
4. summary of analysis, 
5. supporting visualizations with key findings, and
6. top three recommendations.

A Tableau dashboard will enable stakeholders to explore data interactively for both the completed analysis and prospectively to monitor effectiveness of marketing strategies used.

## Structure

I executed this analysis using three tools: R, RStudio and Tableau.  I used a standard R package structure to organize my files.  This file structure is described in the table below.  You can find the Github repository for my work [here](https://github.com/dtminnick/cyclistic).

| Folder         | Description              |
| :------------- | :----------------------- |
| data-raw       | Contains cleaned data stored in .rda format, i.e. R data files. |
| inst/extdata   | Contains downloaded source data, reference files and outputs.  Note that source data files are not pushed to the Github repository due to size.  Refer to prepare.Rmd file in the vignettes subfolder for details on how I downloaded source data. |
| man            | Contains documentation for any custom functions I created for this analysis. |
| R              | Contains code for custom functions. |
| tests          | Contains scripts for testing custom functions. |
| vignettes      | Stores notebooks for this analysis in six phases: Ask, Prepare, Process, Analyze, Share and Act; one R markdown file per phase. |
